hello world app
nfq-react-workshop/useful-useless pull request #1
Opened 2018-11-05 10:27 UTC by irmantaszenkus

2018-11-05 11:09 UTC, VytautasLozickas requested changes

2018-11-05 11:09 UTC, VytautasLozickas commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Reiktų turbūt iš karto įsidėti build script'ą kad paleisti parcel

2018-11-05 17:44 UTC, FDiskas approved these changes

2018-11-06 19:46 UTC, FDiskas commented
@VytautasLozickas palik tuos readme :o

2018-11-06 19:48 UTC, FDiskas commented
Ai dabar supratau - nukeliavo jie i master brancha - viskas ok

2018-11-06 22:04 UTC, closed without merging